---

- name: Add a new rule to the pg_hba.conf file to allow connections from the web server
  tags: postgresql
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{ db_servers_postgresql_version }}/main/pg_hba.conf
    address: 192.168.0.103/32
    contype: host
    databases: "{{ database_name }}"
    method: md5
    users: "{{ database_username }}"
  notify: Reload postgresql service

- name: Set "listen_addresses" to "*"
  tags: postgresql
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "*"
  become: true
  become_user: postgres
  notify: Restart postgresql service

- name: Create a postgresql user for the Alpha Vantage ETL database
  tags: postgresql
  community.postgresql.postgresql_user:
    name: "{{ database_username }}"
    password: "{{ database_user_password }}"
  become: true
  become_user: postgres

- name: Create an Alpha Vantage ETL database
  tags: postgresql
  community.postgresql.postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_username }}"
  become: true
  become_user: postgres
